// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilzxvbqzavblsqozdrvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlsenh2YnF6YXZibHNxb3pkcnZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTMxNzYsImV4cCI6MjA2NzIyOTE3Nn0.AH-dl9ob2H_ZeklC0lLYYAivM8WKa5JLdM-O7lYszXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});